### ISSUE TITLE
Configurable hotkeys

### ISSUE THREAD

**Issue by piranha** [JulianWels/tabby#17]
Hey Julian! I've been looking through Firefox Extensions for something like emacs buffer-switch, and tabby seems to be the best of "cmd-t" like switchers. The only downside right now is that shortcut for calling it up is not configurable, and for me on a Mac `opt-space` is busy with Alfred already. I'm not sure how hard it is to make shortcut configurable, but... do you accept feature requests? 😁

**Comment by JulianWels** [comment]
Hi! Happy to hear that you like the extension :)
The shortcut is managed by the browser, so you can manage it from `about:addons` or `chrome://extensions/`.

When you go to the tabby settings (by clicking on the cat-icon), there is a link to the support page of your browser. [This is the support article for Firefox](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox) — it's hard to find when you don't know it's there haha.

Hope that helps!

**Comment by piranha** [comment]
Wow, discoverability of this is amazingly bad! Who ever thought that hiding this is in an obscure menu is a good idea...

Thanks!
